-- ── Schema ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id            SERIAL PRIMARY KEY,
    username      VARCHAR(50) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cars (
    id        SERIAL PRIMARY KEY,
    make      VARCHAR(50)  NOT NULL,
    model     VARCHAR(50)  NOT NULL,
    color     VARCHAR(50)  NOT NULL,
    condition VARCHAR(20)  NOT NULL,
    price     INTEGER      NOT NULL
);

-- ── Seed cars ────────────────────────────────────────────────

INSERT INTO cars (make, model, color, condition, price) VALUES
('Chevrolet',     'Malibu',        'Burgundy',     'Excellent', 31100),
('Chevrolet',     'Traverse',      'Graphite',     'Excellent', 49700),
('Honda',         'Civic',         'Silver',       'Excellent', 38600),
('GMC',           'Sierra',        'Graphite',     'Excellent', 67700),
('Audi',          'Q5',            'Orange',       'Good',      29300),
('Subaru',        'Ascent',        'Champagne',    'Good',      24700),
('Hyundai',       'Ioniq 5',       'Pearl White',  'Excellent', 32400),
('Chevrolet',     'Equinox',       'Midnight Blue','Good',      21100),
('Jeep',          'Gladiator',     'Gray',         'Poor',      26400),
('Ford',          'Bronco',        'Charcoal',     'Fair',      32400),
('Porsche',       'Cayenne',       'Silver',       'Excellent', 76900),
('Volkswagen',    'Jetta',         'Navy',         'Fair',      23400),
('Mazda',         'CX-30',         'Midnight Blue','Excellent', 35600),
('Hyundai',       'Palisade',      'Burgundy',     'Fair',      28800),
('Ford',          'Bronco',        'Blue',         'Good',      34000),
('Subaru',        'WRX',           'Bronze',       'Excellent', 31200),
('Nissan',        'Altima',        'Navy',         'Fair',      20600),
('Mercedes-Benz', 'GLC',           'Silver',       'Excellent', 75200),
('Nissan',        'Rogue',         'Dark Green',   'Good',      34900),
('Jeep',          'Grand Cherokee','Burgundy',     'Excellent', 45200),
('Porsche',       'Taycan',        'Bronze',       'Good',      60400),
('Lexus',         'IS',            'Silver',       'Fair',      30700),
('BMW',           'X1',            'Blue',         'Fair',      43300),
('GMC',           'Sierra',        'Bronze',       'Good',      53300),
('Lexus',         'NX',            'Graphite',     'Fair',      26400),
('Chevrolet',     'Traverse',      'Graphite',     'Fair',      30100),
('Chevrolet',     'Equinox',       'Champagne',    'Excellent', 22200),
('Mazda',         'MX-5 Miata',    'Blue',         'Good',      23400),
('Volkswagen',    'Taos',          'Ice Blue',     'Good',      23000),
('Kia',           'K5',            'Blue',         'Good',      38700),
('Lexus',         'RX',            'Pearl White',  'Good',      38500),
('Kia',           'K5',            'Charcoal',     'Excellent', 27900),
('Porsche',       '911',           'Silver',       'Fair',      78500),
('Ford',          'Edge',          'Graphite',     'Fair',      22000),
('Ram',           'ProMaster',     'Blue',         'Excellent', 61700),
('Hyundai',       'Kona',          'Green',        'Fair',      22500),
('Kia',           'Seltos',        'Ice Blue',     'Good',      23900),
('Tesla',         'Model 3',       'Pearl White',  'Excellent', 74300),
('Tesla',         'Model Y',       'Black',        'Excellent', 79400),
('Honda',         'Accord',        'Silver',       'Poor',      16400),
('Ford',          'Bronco',        'Navy',         'Excellent', 55800),
('Hyundai',       'Kona',          'Red',          'Fair',      33300),
('Porsche',       'Taycan',        'Navy',         'Fair',      78100),
('Audi',          'Q5',            'Gray',         'Excellent', 62200),
('Kia',           'Seltos',        'Champagne',    'Good',      37300),
('Honda',         'Ridgeline',     'Gray',         'Excellent', 45900),
('Nissan',        'Altima',        'Navy',         'Excellent', 37600),
('Jeep',          'Grand Cherokee','Champagne',    'Excellent', 58300),
('Tesla',         'Model 3',       'Orange',       'Fair',      64000),
('Volvo',         'XC60',          'White',        'Good',      29700),
('Ford',          'Edge',          'Navy',         'Excellent', 55800),
('Ram',           '1500',          'Bronze',       'Poor',      22400),
('Mercedes-Benz', 'C-Class',       'Bronze',       'Excellent', 89400),
('Jeep',          'Cherokee',      'Champagne',    'Good',      50900),
('BMW',           '5 Series',      'Charcoal',     'Excellent', 39800),
('Porsche',       '911',           'Pearl White',  'Excellent',100300),
('Ram',           'ProMaster',     'Ice Blue',     'Excellent', 67300),
('Ford',          'Edge',          'Blue',         'Excellent', 28500),
('Tesla',         'Model X',       'Gray',         'Poor',      37700),
('Tesla',         'Model 3',       'Silver',       'Good',      64800),
('Porsche',       'Macan',         'Burgundy',     'Excellent',108900),
('Nissan',        'Rogue',         'Burgundy',     'Good',      35700),
('Volkswagen',    'Golf GTI',      'Pearl White',  'Poor',      12200),
('Toyota',        'Tundra',        'Gray',         'Excellent', 29000),
('Lexus',         'NX',            'Red',          'Poor',      21300),
('Tesla',         'Model S',       'Charcoal',     'Excellent', 92600),
('Volvo',         'S60',           'Ice Blue',     'Excellent', 53600),
('Chevrolet',     'Silverado',     'Burgundy',     'Excellent', 29000),
('Volvo',         'XC90',          'Burgundy',     'Excellent', 47800),
('Nissan',        'Rogue',         'Burgundy',     'Good',      24000),
('Honda',         'Civic',         'Champagne',    'Fair',      15900),
('Toyota',        'Prius',         'Red',          'Good',      26000),
('Subaru',        'Ascent',        'Orange',       'Good',      32300),
('Volvo',         'XC60',          'Gray',         'Excellent', 43800),
('Volvo',         'XC60',          'Midnight Blue','Good',      37100),
('Audi',          'Q5',            'White',        'Good',      31100),
('Kia',           'Sportage',      'Navy',         'Good',      26900),
('Volvo',         'V60',           'Red',          'Poor',      24800),
('Subaru',        'Forester',      'Champagne',    'Excellent', 34900),
('Audi',          'A3',            'Navy',         'Excellent', 41100),
('Mercedes-Benz', 'C-Class',       'Dark Green',   'Excellent', 91500),
('Jeep',          'Cherokee',      'Charcoal',     'Fair',      29200),
('Tesla',         'Model 3',       'Green',        'Good',      47800),
('Ford',          'Edge',          'Burgundy',     'Good',      48800),
('Mercedes-Benz', 'S-Class',       'Graphite',     'Good',      33800),
('Chevrolet',     'Equinox',       'Blue',         'Good',      33500),
('Honda',         'Civic',         'Champagne',    'Good',      40600),
('Nissan',        'Pathfinder',    'Ice Blue',     'Excellent', 38900),
('Hyundai',       'Santa Fe',      'White',        'Fair',      13600),
('Lexus',         'GX',            'Green',        'Good',      36200),
('Nissan',        'Frontier',      'Pearl White',  'Good',      20500),
('Volkswagen',    'ID.4',          'Charcoal',     'Good',      27800),
('Mercedes-Benz', 'S-Class',       'Charcoal',     'Good',      43000),
('Audi',          'A3',            'Bronze',       'Good',      38600),
('GMC',           'Acadia',        'Bronze',       'Good',      27200),
('Volkswagen',    'Atlas',         'Green',        'Good',      34900),
('GMC',           'Acadia',        'Orange',       'Good',      39100),
('Lexus',         'IS',            'Blue',         'Good',      48100),
('Lexus',         'GX',            'Pearl White',  'Excellent', 53400),
('Volkswagen',    'Tiguan',        'Green',        'Excellent', 23500);
